{% set name = "pybktree" %}
{% set version = "1.1" %}
{% set sha256hash = "eec0037cdd3d7553e6d72435a4379bede64be17c6712f149e485169638154d2b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  https://pypi.io/packages/source/p/pybktree-1.1.tar.gz 
  sha256: {{ sha256hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
  run:
    - python


about:
  home: https://github.com/Jetsetter/pybktree
  license: MIT License
  license_family: MIT
  summary: 'pybktree is a generic, pure Python implementation of a BK-tree
  	   data structure, which allows fast querying of "close" matches'
  dev_url: https://github.com/Jetsetter/pybktree
